### PR TITLE
Handle literal 'null' case

### PR DESCRIPTION
**Pull request by snadorp**
I was running into the issue that I was not able to apply the initial `VectorExtension()` Mmigration in my Django application:

``` sh
make migrate
(cd src && python manage.py makemigrations)
INFO 2023-08-09 16:40:00,257 utils Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO 2023-08-09 16:40:00,257 utils NumExpr defaulting to 8 threads.
No changes detected
(cd src && python manage.py migrate)
INFO 2023-08-09 16:40:01,589 utils Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO 2023-08-09 16:40:01,589 utils NumExpr defaulting to 8 threads.
Operations to perform:
  Apply all migrations: admin, auth, client, contenttypes, users
Running migrations:
  Applying candidate.0018_candidate_skill_embeddings...null
Traceback (most recent call last):
  File "/path/to/your/manage.py", line 22, in <module>
    main()
  File "/path/to/your/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/path/to/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/path/to/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path/to/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/path/to/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/path/to/venv/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/path/to/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 668, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 359, in column_sql
    " ".join(
  File "/path/to/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 310, in _iter_column_sql
    default_value = self.effective_default(field)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 429, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 954, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 947, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/pgvector/django/__init__.py", line 41, in get_prep_value
    return to_db(value)
           ^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/pgvector/utils/__init__.py", line 37, in to_db
    return '[' + ','.join([str(float(v)) for v in value]) + ']'
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/pgvector/utils/__init__.py", line 37, in <listcomp>
```

Initial migration looks like this:

```python
from django.db import migrations
from pgvector.django import VectorExtension, VectorField


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0017_other"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="user",
            name="skill_embeddings",
            field=VectorField(default="null", dimensions=1536),
            preserve_default=False,
        ),
    ]

```

### CODE REVIEW

**Comment by ankane** [comment]
Hi @snadorp, thanks for the PR, but you can use `None` for this (`'null'` is not a valid vector literal).

**Comment by snadorp** [comment]
You mean in the migration?
That has been generated by `makemigration` so maybe that might need fixing then.

**Comment by ankane** [comment]
Can you share what the model looks like? Also, any chance `'null'` was set as the default value when running `makemigration`?

**Comment by snadorp** [comment]
@ankane The model was as simple as:
```python
class Thing(django.model):
   ...
    skill_embeddings = VectorField(dimensions=1536)
```
which then generated the migration I shared above. I prepended the `VectorExtension(),` operation by hand.

**Pull request closed without merging**
