### PR TITLE
Support the `peewee` ORM

### PR DESCRIPTION
**Pull request by bormanjo**
Feature request [here](https://github.com/pgvector/pgvector-python/issues/26).

Adds:

- [x] Support declaring `VectorField`s and basic distance metrics
- [x] ~Support vector-based indexes~

### CODE REVIEW

**Comment by bormanjo** [comment]
Index support should already be available through the existing peewee classes

**Comment by bormanjo** [comment]
@ankane @maparent @jerinpetergeorge @kwood - please let me know your thoughts on this PR when you can :smile:

**Comment by maparent** [comment]
Not familiar with peewee, no comment from me.

**Comment by ankane** [comment]
Thanks @bormanjo! Added in the commit above.

(also, please don't tag other contributors in PRs)

**Pull request closed without merging**
